name: dartify_json
description: "Dart Class Generator from JSON is a tool that automatically converts JSON files into Dart classes. It creates complete classes with fields, constructors, fromJson, and toJson methods, making it easy to handle JSON data in Flutter and Dart applications."
version: 0.0.2
homepage:

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  args:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

